baseURL = "http://bloc.mespilus.org"
title = "Mespilus - Cooperativa de Consum Responsable del Poblenou"
theme = "dimension"
languageCode = "es-ca"
defaultContentLanguage = "ca"
enableRobotsTXT = true
disableRSS = true
publishDir = "docs"

[params]
  title = "Mespilus"
  description = '<!--[-->Cooperativa de Consum Responsable del Poblenou<!--]-->'
  logo = "fa-shopping-cart"
  copyright = "27 Juli 2017"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "https://www.facebook.com/Mespiluspoblenou"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/mespilus"

[languages]
[languages.ca]
languageName = "Catalá"
weight = 1
title = "Mespilus"

[languages.es]
languageName = "Español"
weight = 2
title = "Mespilus"
description = '<!--[-->Cooperativa de Consumo Responsable de Poblenou<!--]-->'

[languages.en]
languageName = "English"
weight = 3
title = "Mespilus"
description = "<!--[-->Responsible Buyers' Cooperative of Poblenou<!--]-->"